server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/db2022?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT
    username: root
    password: huangyanliang067


mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.athuang.springcloud.entities    # 所有Entity别名类所在包
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
      defaultZone: http://eureka7001.com:7001/eureka